#! /bin/bash
# generated by ./collect_git_remote_add_recusively.sh 
pushd $(dirname $0)

pushd .. ; git remote add drewm git://github.com/drewm/PHPMailer.git ; popd
pushd .. ; git remote add fuery git://github.com/fuery/PHPMailer.git ; popd
pushd .. ; git remote add garoevans git://github.com/garoevans/PHPMailer.git ; popd
pushd .. ; git remote add hallgren git://github.com/HallgrenNetworks/phpmailer.git ; popd
pushd .. ; git remote add kyle_mathews git://github.com/KyleAMathews/phpmailer.git ; popd
pushd .. ; git remote add marcfruchter git://github.com/marcfruchter/PHPMailer.git ; popd
pushd .. ; git remote add mwhite git://github.com/mwhite/phpmailer.git ; popd
pushd .. ; git remote add qoqa git://github.com/qoqa/phpmailer.git ; popd
pushd .. ; git remote add svn ../phpmailer ; popd
pushd .. ; git remote add synchro git://github.com/Synchro/PHPMailer.git ; popd
pushd .. ; git remote add willi_gant git://github.com/WilliGant/PHPMailer.git ; popd

popd

